export const Countries =
[
  { name: 'United States', code: 'ar' },
  { name: 'Argentina', code: 'ar' },
  { name: 'Australia', code: 'ar' },
  { name: 'Austria', code: 'ar' },
  { name: 'Belgium', code: 'ar' },
  { name: 'Brazil', code: 'ar' },
  { name: 'Bulgaria', code: 'ar' },
  { name: 'Canada', code: 'ar' },
  { name: 'China', code: 'ar' },
  { name: 'Colombia', code: 'ar' },
  { name: 'Czech Republic', code: 'ar' },
  { name: 'Egypt', code: 'ar' },
  { name: 'France', code: 'ar' },
  { name: 'Germany', code: 'ar' },
  { name: 'Greece', code: 'ar' },
  { name: 'Hong Kong', code: 'ar' },
  { name: 'Hungary', code: 'ar' },
  { name: 'India', code: 'ar' },
  { name: 'Indonesia', code: 'ar' },
  { name: 'Ireland', code: 'ar' },
  { name: 'Israel', code: 'ar' },
  { name: 'Italy', code: 'ar' },
  { name: 'Japan', code: 'ar' },
  { name: 'Latvia', code: 'ar' },
  { name: 'Lithuania', code: 'ar' },
  { name: 'Malaysia', code: 'ar' },
  { name: 'Mexico', code: 'ar' },
  { name: 'Morocco', code: 'ar' },
  { name: 'Netherlands', code: 'ar' },
  { name: 'New Zealand', code: 'ar' },
  { name: 'Nigeria', code: 'ar' },
  { name: 'Norway', code: 'ar' },
  { name: 'Philippines', code: 'ar' },
  { name: 'Poland', code: 'ar' },
  { name: 'Portugal', code: 'ar' },
  { name: 'Romania', code: 'ar' },
  { name: 'Saudi Arabia', code: 'ar' },
  { name: 'Serbia', code: 'ar' },
  { name: 'Singapore', code: 'ar' },
  { name: 'Slovakia', code: 'ar' },
  { name: 'Slovenia', code: 'ar' },
  { name: 'South Africa', code: 'ar' },
  { name: 'South Korea', code: 'ar' },
  { name: 'Sweden', code: 'ar' },
  { name: 'Switzerland', code: 'ar' },
  { name: 'Taiwan', code: 'ar' },
  { name: 'Thailand', code: 'ar' },
  { name: 'Turkey', code: 'ar' },
  { name: 'United Arab Emirates', code: 'ar' },
  { name: 'Ukraine', code: 'ar' },
  { name: 'United Kingdom', code: 'ar' },
  { name: 'Venezuela', code: 'ar' }
]
